# Generated by Django 2.0.2 on 2019-06-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='Pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
